version: '3.9'
services:
  coupon_service_local:
    build:
      context: '.'
      dockerfile: Dockerfile
    environment:
      - API_PORT=80
      - API_ENV=development
      - API_TIME_ALIVE=1y
    ports:
      - 8082:80
  coupon_service:
    image: matheuspolitano/couponservice:latest
    environment:
      - API_PORT=80
      - API_ENV=development
      - API_TIME_ALIVE=1y
    ports:
      - 8083:80
